use_frameworks!

target 'POPDataSource_Example' do
  pod 'POPDataSource', :path => '../'

  target 'POPDataSource_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
